name: Lint and Validate
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "feature/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install linters
        run: |
          pip install ruff yamllint
      - name: Lint Python
        run: ruff check . --output-format=github
      - name: Lint YAML
        run: yamllint .
      - name: Lint JSON
        run: |
          find . -name '*.json' -print0 | xargs -0 -I {} python -m json.tool {} /dev/null