name: Run Pytest

on:
  pull_request:         # Run tests on PRs into main
    branches:
      - main
  push:                 # Also run on direct pushes to feature branches
    branches:
      - "feature/**"

jobs:
  tests:
    name: Run unit tests with pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
